#!/bin/sh

CURRENT=$(pactl get-sink-volume @DEFAULT_SINK@ | grep -e '%' | sed 's/ //g' | cut -d "/" -f 2 | sed 's/%//')
MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | grep -e 'Mute' | sed 's/ //g' | cut -d ":" -f 2)

up() {
	new=$(($CURRENT + 5))
	if [ $new -lt 100 ]; then
		pactl set-sink-volume @DEFAULT_SINK@ $new%
	else
		pactl set-sink-volume @DEFAULT_SINK@ 100%
	fi
}

down() {
	new=$(($CURRENT - 5))
	if [ $new -gt 0 ]; then
		pactl set-sink-volume @DEFAULT_SINK@ $new%
	else
		pactl set-sink-volume @DEFAULT_SINK@ 0%
	fi
}

toggle_mute() {
	if [ "$MUTED" = "no" ]; then
		pactl set-sink-mute @DEFAULT_SINK@ 1
	else
		pactl set-sink-mute @DEFAULT_SINK@ 0
	fi
}

if [[ "$1" == "--up" ]]; then
	up
elif [[ "$1" == "--down" ]]; then
	down
elif [ "$1" = "--mute" ]; then
	toggle_mute
fi
